package cineinterfaz.vista;

import cineinterfaz.controlador.ControladorCompraWindow;

/**
 * @author Andrés Cabero Mata
 * @author Patricia Aguado Labrador
 *
 * Vista de compra.
 */
public class CompraWindow extends javax.swing.JFrame {

    private ModeloCineInterfaz miModelo;
    private ControladorCompraWindow miControlador;

    /**
     * Creates new form CompraWindow
     */
    public CompraWindow(ModeloCineInterfaz miModelo) {
        initComponents();
        this.miModelo = miModelo;
        miControlador = new ControladorCompraWindow(this, miModelo);
        establecerPelicula();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuBar = new javax.swing.JPanel();
        cartelera = new javax.swing.JButton();
        proximos = new javax.swing.JButton();
        infantil = new javax.swing.JButton();
        imagenCine = new javax.swing.JButton();
        cartel = new javax.swing.JPanel();
        pelicula = new javax.swing.JLabel();
        duracion = new javax.swing.JLabel();
        tituloLabel = new javax.swing.JLabel();
        titulo = new javax.swing.JLabel();
        diaLabel = new javax.swing.JLabel();
        horaLabel = new javax.swing.JLabel();
        entradasLabel = new javax.swing.JLabel();
        precioLabel = new javax.swing.JLabel();
        hora = new javax.swing.JLabel();
        dia = new javax.swing.JLabel();
        entradas = new javax.swing.JLabel();
        precio = new javax.swing.JLabel();
        totalLabel = new javax.swing.JLabel();
        total = new javax.swing.JLabel();
        pagar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menuBar.setLayout(new java.awt.GridLayout(1, 4, 10, 0));

        cartelera.setText("Cartelera");
        cartelera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carteleraActionPerformed(evt);
            }
        });
        menuBar.add(cartelera);

        proximos.setText("Próximos");
        proximos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proximosActionPerformed(evt);
            }
        });
        menuBar.add(proximos);

        infantil.setText("Infantil");
        infantil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                infantilActionPerformed(evt);
            }
        });
        menuBar.add(infantil);

        imagenCine.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cineuvalogo.png"))); // NOI18N
        imagenCine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imagenCineActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout cartelLayout = new javax.swing.GroupLayout(cartel);
        cartel.setLayout(cartelLayout);
        cartelLayout.setHorizontalGroup(
            cartelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cartelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pelicula, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))
        );
        cartelLayout.setVerticalGroup(
            cartelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pelicula, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
        );

        tituloLabel.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        tituloLabel.setText("Título:");

        titulo.setFont(new java.awt.Font("Noto Sans", 0, 18)); // NOI18N
        titulo.setText("titulo");

        diaLabel.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        diaLabel.setText("Día:");

        horaLabel.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        horaLabel.setText("Hora:");

        entradasLabel.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        entradasLabel.setText("Entradas:");

        precioLabel.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        precioLabel.setText("Precio por entrada:");

        hora.setFont(new java.awt.Font("Noto Sans", 0, 18)); // NOI18N
        hora.setText("hora");

        dia.setFont(new java.awt.Font("Noto Sans", 0, 18)); // NOI18N
        dia.setText("dia");

        entradas.setFont(new java.awt.Font("Noto Sans", 0, 18)); // NOI18N
        entradas.setText("entradas");

        precio.setFont(new java.awt.Font("Noto Sans", 0, 18)); // NOI18N
        precio.setText("precio");

        totalLabel.setFont(new java.awt.Font("Noto Sans", 0, 18)); // NOI18N
        totalLabel.setText("TOTAL:");

        total.setFont(new java.awt.Font("Noto Sans", 0, 20)); // NOI18N
        total.setText("total");

        pagar.setText("Pagar");
        pagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pagarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(duracion)
                            .addComponent(cartel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(imagenCine, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addComponent(menuBar, javax.swing.GroupLayout.PREFERRED_SIZE, 568, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(precioLabel)
                            .addComponent(totalLabel)
                            .addComponent(entradasLabel)
                            .addComponent(diaLabel)
                            .addComponent(horaLabel)
                            .addComponent(tituloLabel))
                        .addGap(275, 275, 275)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(hora)
                            .addComponent(titulo)
                            .addComponent(dia)
                            .addComponent(entradas)
                            .addComponent(precio)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(total)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 211, Short.MAX_VALUE)
                                .addComponent(pagar, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(67, 67, 67))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(imagenCine, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(menuBar, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(titulo)
                            .addComponent(tituloLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dia)
                            .addComponent(diaLabel))
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(hora)
                            .addComponent(horaLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(entradas)
                            .addComponent(entradasLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(precio)
                            .addComponent(precioLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(totalLabel)
                            .addComponent(total))
                        .addGap(81, 81, 81))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(pagar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cartel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(duracion)
                        .addContainerGap(29, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void carteleraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carteleraActionPerformed
        miControlador.cartelera();
    }//GEN-LAST:event_carteleraActionPerformed

    private void proximosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proximosActionPerformed
        miControlador.proximos();
    }//GEN-LAST:event_proximosActionPerformed

    private void infantilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_infantilActionPerformed
        miControlador.infantil();
    }//GEN-LAST:event_infantilActionPerformed

    private void imagenCineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imagenCineActionPerformed
        miControlador.home();
    }//GEN-LAST:event_imagenCineActionPerformed

    private void pagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pagarActionPerformed
        miControlador.pagar();
    }//GEN-LAST:event_pagarActionPerformed

    public void establecerPelicula() {
        pelicula.setIcon(new javax.swing.ImageIcon(getClass().getResource(miModelo.getPelicula().getCartel())));
        titulo.setText(miModelo.getPelicula().getTitulo());
        duracion.setText(String.valueOf(miModelo.getPelicula().getDuracion()) + " min");
        dia.setText(miModelo.getDia());
        hora.setText(miModelo.getHora());
        entradas.setText(String.valueOf(miModelo.getNEntradas()));
        precio.setText(String.valueOf(miModelo.getPrecio()) + "€");
        total.setText(String.valueOf(miModelo.getPrecio() * miModelo.getNEntradas()) + "€");
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel cartel;
    private javax.swing.JButton cartelera;
    private javax.swing.JLabel dia;
    private javax.swing.JLabel diaLabel;
    private javax.swing.JLabel duracion;
    private javax.swing.JLabel entradas;
    private javax.swing.JLabel entradasLabel;
    private javax.swing.JLabel hora;
    private javax.swing.JLabel horaLabel;
    private javax.swing.JButton imagenCine;
    private javax.swing.JButton infantil;
    private javax.swing.JPanel menuBar;
    private javax.swing.JButton pagar;
    private javax.swing.JLabel pelicula;
    private javax.swing.JLabel precio;
    private javax.swing.JLabel precioLabel;
    private javax.swing.JButton proximos;
    private javax.swing.JLabel titulo;
    private javax.swing.JLabel tituloLabel;
    private javax.swing.JLabel total;
    private javax.swing.JLabel totalLabel;
    // End of variables declaration//GEN-END:variables
}
