
package cineinterfaz.vista;

import cineinterfaz.controlador.ControladorInfantilWindow;

/**
 * @author Andrés Cabero Mata
 * @author Patricia Aguado Labrador
 *
 * Vista de infantil.
 */
public class InfantilWindow extends javax.swing.JFrame {

    private ControladorInfantilWindow miControlador;
    private ModeloCineInterfaz miModelo;

    /**
     * Creates new form ProximosWindow
     */
    public InfantilWindow(ModeloCineInterfaz miModelo) {
        initComponents();
        this.miModelo = miModelo;
        miControlador = new ControladorInfantilWindow(this, miModelo);
        establecerInfantil();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imagenCine = new javax.swing.JButton();
        menuBar = new javax.swing.JPanel();
        cartelera = new javax.swing.JButton();
        proximos = new javax.swing.JButton();
        infantil = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        inf1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        inf2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        inf3 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        inf4 = new javax.swing.JLabel();
        populares = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        imagenCine.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cineuvalogo.png"))); // NOI18N
        imagenCine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imagenCineActionPerformed(evt);
            }
        });

        menuBar.setLayout(new java.awt.GridLayout(1, 4, 10, 0));

        cartelera.setText("Cartelera");
        cartelera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carteleraActionPerformed(evt);
            }
        });
        menuBar.add(cartelera);

        proximos.setText("Próximos");
        proximos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proximosActionPerformed(evt);
            }
        });
        menuBar.add(proximos);

        infantil.setText("Infantil");
        menuBar.add(infantil);

        jPanel1.setLayout(new java.awt.GridLayout(1, 5));

        inf1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                inf1MouseReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(inf1)
                .addGap(0, 259, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(inf1)
                .addGap(0, 286, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2);

        inf2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                inf2MouseReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(inf2)
                .addGap(0, 259, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(inf2)
                .addGap(0, 286, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3);

        inf3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                inf3MouseReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(inf3)
                .addGap(0, 259, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(inf3)
                .addGap(0, 286, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel4);

        inf4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                inf4MouseReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(inf4)
                .addGap(0, 259, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(inf4)
                .addGap(0, 286, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel5);

        populares.setFont(new java.awt.Font("Noto Sans", 1, 48)); // NOI18N
        populares.setForeground(new java.awt.Color(239, 106, 60));
        populares.setText("Infantil");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(imagenCine)
                        .addGap(58, 58, 58)
                        .addComponent(menuBar, javax.swing.GroupLayout.PREFERRED_SIZE, 568, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(191, 191, 191))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 0, Short.MAX_VALUE)
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(populares))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(menuBar, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(imagenCine, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(populares, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void imagenCineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imagenCineActionPerformed
        miControlador.home();
    }//GEN-LAST:event_imagenCineActionPerformed

    private void carteleraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carteleraActionPerformed
        miControlador.cartelera();
    }//GEN-LAST:event_carteleraActionPerformed

    private void proximosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proximosActionPerformed
        miControlador.proximos();
    }//GEN-LAST:event_proximosActionPerformed

    private void inf1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inf1MouseReleased
        miControlador.pelicula(miModelo.getInfantil()[0]);
    }//GEN-LAST:event_inf1MouseReleased

    private void inf2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inf2MouseReleased
        miControlador.pelicula(miModelo.getInfantil()[1]);
    }//GEN-LAST:event_inf2MouseReleased

    private void inf3MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inf3MouseReleased
        miControlador.pelicula(miModelo.getInfantil()[2]);
    }//GEN-LAST:event_inf3MouseReleased

    private void inf4MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inf4MouseReleased
        miControlador.pelicula(miModelo.getInfantil()[3]);
    }//GEN-LAST:event_inf4MouseReleased

    public void establecerInfantil() {
        inf1.setIcon(new javax.swing.ImageIcon(getClass().getResource(miModelo.getInfantil()[0].getCartel())));
        inf2.setIcon(new javax.swing.ImageIcon(getClass().getResource(miModelo.getInfantil()[1].getCartel())));
        inf3.setIcon(new javax.swing.ImageIcon(getClass().getResource(miModelo.getInfantil()[2].getCartel())));
        inf4.setIcon(new javax.swing.ImageIcon(getClass().getResource(miModelo.getInfantil()[3].getCartel())));
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cartelera;
    private javax.swing.JButton imagenCine;
    private javax.swing.JLabel inf1;
    private javax.swing.JLabel inf2;
    private javax.swing.JLabel inf3;
    private javax.swing.JLabel inf4;
    private javax.swing.JButton infantil;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel menuBar;
    private javax.swing.JLabel populares;
    private javax.swing.JButton proximos;
    // End of variables declaration//GEN-END:variables
}
