package cineinterfaz.vista;

import cineinterfaz.controlador.ControladorLoginWindow;

/**
 * @author Andrés Cabero Mata
 * @author Patricia Aguado Labrador
 *
 * Vista de login.
 */
public class LoginWindow extends javax.swing.JFrame {

    private ControladorLoginWindow miControlador;
    private ModeloCineInterfaz miModelo;

    /**
     * Creates new form LoginWindow
     */
    public LoginWindow(ModeloCineInterfaz miModelo) {

        initComponents();
        this.miModelo = miModelo;
        miControlador = new ControladorLoginWindow(this, miModelo);
        establecerPelicula();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        inicioSesion = new javax.swing.JPanel();
        emailLabel = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        contrasena = new javax.swing.JPasswordField();
        contrasenaLabel = new javax.swing.JLabel();
        login = new javax.swing.JButton();
        inicioLabel = new javax.swing.JLabel();
        cartel = new javax.swing.JPanel();
        pelicula = new javax.swing.JLabel();
        menuBar = new javax.swing.JPanel();
        cartelera = new javax.swing.JButton();
        proximos = new javax.swing.JButton();
        infantil = new javax.swing.JButton();
        imagenCine = new javax.swing.JButton();
        duracion = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        emailLabel.setText("Email:");

        contrasenaLabel.setText("Contraseña:");

        login.setFont(new java.awt.Font("Ubuntu", 0, 15)); // NOI18N
        login.setText("Iniciar sesión");
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });

        inicioLabel.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        inicioLabel.setText("Inicia sesion para continuar con la compra");

        javax.swing.GroupLayout inicioSesionLayout = new javax.swing.GroupLayout(inicioSesion);
        inicioSesion.setLayout(inicioSesionLayout);
        inicioSesionLayout.setHorizontalGroup(
            inicioSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inicioSesionLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(inicioSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(inicioLabel)
                    .addGroup(inicioSesionLayout.createSequentialGroup()
                        .addGroup(inicioSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(contrasenaLabel)
                            .addComponent(emailLabel))
                        .addGap(45, 45, 45)
                        .addGroup(inicioSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(login, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(email, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(contrasena, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE))))
                .addGap(30, 30, 30))
        );
        inicioSesionLayout.setVerticalGroup(
            inicioSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inicioSesionLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(inicioLabel)
                .addGap(44, 44, 44)
                .addGroup(inicioSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailLabel))
                .addGap(30, 30, 30)
                .addGroup(inicioSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(contrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(contrasenaLabel))
                .addGap(42, 42, 42)
                .addComponent(login)
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout cartelLayout = new javax.swing.GroupLayout(cartel);
        cartel.setLayout(cartelLayout);
        cartelLayout.setHorizontalGroup(
            cartelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cartelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pelicula, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))
        );
        cartelLayout.setVerticalGroup(
            cartelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pelicula, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
        );

        menuBar.setLayout(new java.awt.GridLayout(1, 4, 10, 0));

        cartelera.setText("Cartelera");
        cartelera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carteleraActionPerformed(evt);
            }
        });
        menuBar.add(cartelera);

        proximos.setText("Próximos");
        proximos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proximosActionPerformed(evt);
            }
        });
        menuBar.add(proximos);

        infantil.setText("Infantil");
        infantil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                infantilActionPerformed(evt);
            }
        });
        menuBar.add(infantil);

        imagenCine.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cineuvalogo.png"))); // NOI18N
        imagenCine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imagenCineActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(imagenCine)
                    .addComponent(cartel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(duracion))
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(menuBar, javax.swing.GroupLayout.PREFERRED_SIZE, 568, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(inicioSesion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(191, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(imagenCine, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(menuBar, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cartel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inicioSesion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(duracion)
                .addGap(58, 58, 58))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void carteleraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carteleraActionPerformed
        miControlador.cartelera();
    }//GEN-LAST:event_carteleraActionPerformed

    private void proximosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proximosActionPerformed
        miControlador.proximos();
    }//GEN-LAST:event_proximosActionPerformed

    private void infantilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_infantilActionPerformed
        miControlador.infantil();
    }//GEN-LAST:event_infantilActionPerformed

    private void imagenCineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imagenCineActionPerformed
        miControlador.home();
    }//GEN-LAST:event_imagenCineActionPerformed

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
        miControlador.login();
    }//GEN-LAST:event_loginActionPerformed

    public void establecerPelicula() {
        pelicula.setIcon(new javax.swing.ImageIcon(getClass().getResource(miModelo.getPelicula().getCartel())));
        duracion.setText(String.valueOf(miModelo.getPelicula().getDuracion()) + " min");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel cartel;
    private javax.swing.JButton cartelera;
    private javax.swing.JPasswordField contrasena;
    private javax.swing.JLabel contrasenaLabel;
    private javax.swing.JLabel duracion;
    private javax.swing.JTextField email;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JButton imagenCine;
    private javax.swing.JButton infantil;
    private javax.swing.JLabel inicioLabel;
    private javax.swing.JPanel inicioSesion;
    private javax.swing.JButton login;
    private javax.swing.JPanel menuBar;
    private javax.swing.JLabel pelicula;
    private javax.swing.JButton proximos;
    // End of variables declaration//GEN-END:variables
}
