package cineinterfaz.vista;

import cineinterfaz.controlador.ControladorProximosWindow;

/**
 * @author Andrés Cabero Mata
 * @author Patricia Aguado Labrador
 *
 * Vista de proximos.
 */
public class ProximosWindow extends javax.swing.JFrame {

    private ControladorProximosWindow miControlador;
    private ModeloCineInterfaz miModelo;

    /**
     * Creates new form ProximosWindow
     */
    public ProximosWindow(ModeloCineInterfaz miModelo) {
        initComponents();
        this.miModelo = miModelo;
        miControlador = new ControladorProximosWindow(this, miModelo);
        establecerProximos();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuBar = new javax.swing.JPanel();
        cartelera = new javax.swing.JButton();
        proximos = new javax.swing.JButton();
        infantil = new javax.swing.JButton();
        imagenCine = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        prox1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        prox2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        prox3 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        prox4 = new javax.swing.JLabel();
        proximosLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        menuBar.setLayout(new java.awt.GridLayout(1, 4, 10, 0));

        cartelera.setText("Cartelera");
        cartelera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carteleraActionPerformed(evt);
            }
        });
        menuBar.add(cartelera);

        proximos.setText("Próximos");
        menuBar.add(proximos);

        infantil.setText("Infantil");
        infantil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                infantilActionPerformed(evt);
            }
        });
        menuBar.add(infantil);

        imagenCine.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cineuvalogo.png"))); // NOI18N
        imagenCine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imagenCineActionPerformed(evt);
            }
        });

        jPanel1.setLayout(new java.awt.GridLayout(1, 5));

        prox1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                prox1MouseReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(prox1)
                .addGap(0, 259, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(prox1)
                .addGap(0, 286, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2);

        prox2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                prox2MouseReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(prox2)
                .addGap(0, 259, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(prox2)
                .addGap(0, 286, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3);

        prox3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                prox3MouseReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(prox3)
                .addGap(0, 259, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(prox3)
                .addGap(0, 286, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel4);

        prox4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                prox4MouseReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(prox4)
                .addGap(0, 259, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(prox4)
                .addGap(0, 286, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel5);

        proximosLabel.setFont(new java.awt.Font("Noto Sans", 1, 48)); // NOI18N
        proximosLabel.setForeground(new java.awt.Color(239, 106, 60));
        proximosLabel.setText("Próximos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 0, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(imagenCine)
                        .addGap(58, 58, 58)
                        .addComponent(menuBar, javax.swing.GroupLayout.PREFERRED_SIZE, 568, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(191, 191, 191))))
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(proximosLabel))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(menuBar, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(imagenCine, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(proximosLabel)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void imagenCineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imagenCineActionPerformed
        miControlador.home();
    }//GEN-LAST:event_imagenCineActionPerformed

    private void carteleraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carteleraActionPerformed
        miControlador.cartelera();
    }//GEN-LAST:event_carteleraActionPerformed

    private void infantilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_infantilActionPerformed
        miControlador.infantil();
    }//GEN-LAST:event_infantilActionPerformed

    private void prox1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_prox1MouseReleased
        miControlador.pelicula(miModelo.getProximos()[0]);

    }//GEN-LAST:event_prox1MouseReleased

    private void prox2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_prox2MouseReleased
        miControlador.pelicula(miModelo.getProximos()[1]);
    }//GEN-LAST:event_prox2MouseReleased

    private void prox3MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_prox3MouseReleased
        miControlador.pelicula(miModelo.getProximos()[2]);
    }//GEN-LAST:event_prox3MouseReleased

    private void prox4MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_prox4MouseReleased
        miControlador.pelicula(miModelo.getProximos()[3]);
    }//GEN-LAST:event_prox4MouseReleased

    public void establecerProximos() {
        prox1.setIcon(new javax.swing.ImageIcon(getClass().getResource(miModelo.getProximos()[0].getCartel())));
        prox2.setIcon(new javax.swing.ImageIcon(getClass().getResource(miModelo.getProximos()[1].getCartel())));
        prox3.setIcon(new javax.swing.ImageIcon(getClass().getResource(miModelo.getProximos()[2].getCartel())));
        prox4.setIcon(new javax.swing.ImageIcon(getClass().getResource(miModelo.getProximos()[3].getCartel())));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cartelera;
    private javax.swing.JButton imagenCine;
    private javax.swing.JButton infantil;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel menuBar;
    private javax.swing.JLabel prox1;
    private javax.swing.JLabel prox2;
    private javax.swing.JLabel prox3;
    private javax.swing.JLabel prox4;
    private javax.swing.JButton proximos;
    private javax.swing.JLabel proximosLabel;
    // End of variables declaration//GEN-END:variables
}
